// Generated by cargo xtask generate. Do not edit.
import Foundation

public let apiVersion: UInt64 = 1
public let maxMessageBytes = 1_048_576

private struct WireKey: CodingKey {
  let stringValue: String
  var intValue: Int? { nil }
  init(_ value: String) { stringValue = value }
  init?(stringValue: String) { self.init(stringValue) }
  init?(intValue: Int) { return nil }
}

private func checkKeys(_ decoder: Decoder, _ allowed: Set<String>) throws {
  let box = try decoder.container(keyedBy: WireKey.self)
  guard Set(box.allKeys.map(\.stringValue)).isSubset(of: allowed) else {
    throw DecodingError.dataCorrupted(
      .init(codingPath: decoder.codingPath, debugDescription: "Unknown field"))
  }
}

public enum Source: String, Codable, Sendable, CaseIterable {
  case catalog = "catalog"
  case library = "library"
  case collection = "collection"
}

public enum Kind: String, Codable, Sendable, CaseIterable {
  case song = "song"
  case album = "album"
  case artist = "artist"
  case playlist = "playlist"
  case station = "station"
}

public enum Scope: String, Codable, Sendable, CaseIterable {
  case library = "library"
  case recent = "recent"
  case home = "home"
  case favorites = "favorites"
  case history = "history"
  case collections = "collections"
  case collection = "collection"
}

public enum Order: String, Codable, Sendable, CaseIterable {
  case name = "name"
  case artist = "artist"
  case recent = "recent"
}

public enum Authorization: String, Codable, Sendable, CaseIterable {
  case notDetermined = "not_determined"
  case restricted = "restricted"
  case denied = "denied"
  case authorized = "authorized"
}

public enum RepeatMode: String, Codable, Sendable, CaseIterable {
  case off = "off"
  case one = "one"
  case all = "all"
}

public enum Control: String, Codable, Sendable, CaseIterable {
  case toggle = "toggle"
  case pause = "pause"
  case stop = "stop"
  case next = "next"
  case previous = "previous"
}

public enum Placement: String, Codable, Sendable, CaseIterable {
  case replace = "replace"
  case next = "next"
  case last = "last"
}

public enum LyricsStatus: String, Codable, Sendable, CaseIterable {
  case synced = "synced"
  case plain = "plain"
  case instrumental = "instrumental"
  case missing = "missing"
}

public enum ErrorCode: String, Codable, Sendable, CaseIterable {
  case invalidRequest = "invalid_request"
  case unsupportedVersion = "unsupported_version"
  case notAuthorized = "not_authorized"
  case signInRequired = "sign_in_required"
  case subscriptionRequired = "subscription_required"
  case unavailable = "unavailable"
  case network = "network"
  case notFound = "not_found"
  case storage = "storage"
  case conflict = "conflict"
  case busy = "busy"
  case cancelled = "cancelled"
  case internalError = "internal_error"
}

public struct Empty: Codable, Sendable, Equatable {
  public init() {
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, [])
  }
}

public struct ItemRef: Codable, Sendable, Equatable {
  public var id: String
  public var source: Source
  public var kind: Kind
  public init(id: String, source: Source, kind: Kind) {
    self.id = id
    self.source = source
    self.kind = kind
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["id", "source", "kind"])
    let box = try decoder.container(keyedBy: WireKey.self)
    id = try box.decode(String.self, forKey: WireKey("id"))
    source = try box.decode(Source.self, forKey: WireKey("source"))
    kind = try box.decode(Kind.self, forKey: WireKey("kind"))
  }
}

public struct Item: Codable, Sendable, Equatable {
  public var ref: ItemRef
  public var title: String
  public var artist: String
  public var album: String
  public var duration: Double?
  public var artworkUrl: String?
  public var releaseDate: String?
  public var albumRef: ItemRef?
  public var artistRef: ItemRef?
  public init(
    ref: ItemRef, title: String, artist: String, album: String, duration: Double? = nil,
    artworkUrl: String? = nil, releaseDate: String? = nil, albumRef: ItemRef? = nil,
    artistRef: ItemRef? = nil
  ) {
    self.ref = ref
    self.title = title
    self.artist = artist
    self.album = album
    self.duration = duration
    self.artworkUrl = artworkUrl
    self.releaseDate = releaseDate
    self.albumRef = albumRef
    self.artistRef = artistRef
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(
      decoder,
      [
        "ref", "title", "artist", "album", "duration", "artworkUrl", "releaseDate", "albumRef",
        "artistRef",
      ])
    let box = try decoder.container(keyedBy: WireKey.self)
    ref = try box.decode(ItemRef.self, forKey: WireKey("ref"))
    title = try box.decode(String.self, forKey: WireKey("title"))
    artist = try box.decode(String.self, forKey: WireKey("artist"))
    album = try box.decode(String.self, forKey: WireKey("album"))
    duration = try box.decodeIfPresent(Double.self, forKey: WireKey("duration"))
    artworkUrl = try box.decodeIfPresent(String.self, forKey: WireKey("artworkUrl"))
    releaseDate = try box.decodeIfPresent(String.self, forKey: WireKey("releaseDate"))
    albumRef = try box.decodeIfPresent(ItemRef.self, forKey: WireKey("albumRef"))
    artistRef = try box.decodeIfPresent(ItemRef.self, forKey: WireKey("artistRef"))
  }
}

public struct QueueEntry: Codable, Sendable, Equatable {
  public var id: String
  public var item: Item?
  public init(id: String, item: Item? = nil) {
    self.id = id
    self.item = item
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["id", "item"])
    let box = try decoder.container(keyedBy: WireKey.self)
    id = try box.decode(String.self, forKey: WireKey("id"))
    item = try box.decodeIfPresent(Item.self, forKey: WireKey("item"))
  }
}

public struct PlayerState: Codable, Sendable, Equatable {
  public var current: Item?
  public var playing: Bool
  public var position: Double
  public var queueCount: UInt64
  public var queueRevision: UInt64
  public var updatedAt: Double
  public var currentEntryId: String?
  public var repeatMode: RepeatMode
  public var shuffle: Bool
  public var canSeek: Bool
  public init(
    current: Item? = nil, playing: Bool, position: Double, queueCount: UInt64,
    queueRevision: UInt64, updatedAt: Double, currentEntryId: String? = nil, repeatMode: RepeatMode,
    shuffle: Bool, canSeek: Bool
  ) {
    self.current = current
    self.playing = playing
    self.position = position
    self.queueCount = queueCount
    self.queueRevision = queueRevision
    self.updatedAt = updatedAt
    self.currentEntryId = currentEntryId
    self.repeatMode = repeatMode
    self.shuffle = shuffle
    self.canSeek = canSeek
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(
      decoder,
      [
        "current", "playing", "position", "queueCount", "queueRevision", "updatedAt",
        "currentEntryId", "repeatMode", "shuffle", "canSeek",
      ])
    let box = try decoder.container(keyedBy: WireKey.self)
    current = try box.decodeIfPresent(Item.self, forKey: WireKey("current"))
    playing = try box.decode(Bool.self, forKey: WireKey("playing"))
    position = try box.decode(Double.self, forKey: WireKey("position"))
    queueCount = try box.decode(UInt64.self, forKey: WireKey("queueCount"))
    queueRevision = try box.decode(UInt64.self, forKey: WireKey("queueRevision"))
    updatedAt = try box.decode(Double.self, forKey: WireKey("updatedAt"))
    currentEntryId = try box.decodeIfPresent(String.self, forKey: WireKey("currentEntryId"))
    repeatMode = try box.decode(RepeatMode.self, forKey: WireKey("repeatMode"))
    shuffle = try box.decode(Bool.self, forKey: WireKey("shuffle"))
    canSeek = try box.decode(Bool.self, forKey: WireKey("canSeek"))
  }
}

public struct QueuePage: Codable, Sendable, Equatable {
  public var entries: [QueueEntry]
  public var nextOffset: UInt64?
  public var revision: UInt64
  public var total: UInt64
  public init(entries: [QueueEntry], nextOffset: UInt64? = nil, revision: UInt64, total: UInt64) {
    self.entries = entries
    self.nextOffset = nextOffset
    self.revision = revision
    self.total = total
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["entries", "nextOffset", "revision", "total"])
    let box = try decoder.container(keyedBy: WireKey.self)
    entries = try box.decode([QueueEntry].self, forKey: WireKey("entries"))
    nextOffset = try box.decodeIfPresent(UInt64.self, forKey: WireKey("nextOffset"))
    revision = try box.decode(UInt64.self, forKey: WireKey("revision"))
    total = try box.decode(UInt64.self, forKey: WireKey("total"))
  }
}

public struct QueueParams: Codable, Sendable, Equatable {
  public var offset: UInt64
  public var revision: UInt64?
  public init(offset: UInt64, revision: UInt64? = nil) {
    self.offset = offset
    self.revision = revision
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["offset", "revision"])
    let box = try decoder.container(keyedBy: WireKey.self)
    offset = try box.decode(UInt64.self, forKey: WireKey("offset"))
    revision = try box.decodeIfPresent(UInt64.self, forKey: WireKey("revision"))
  }
}

public struct Collection: Codable, Sendable, Equatable {
  public var id: String
  public var name: String
  public var description: String
  public var count: UInt64
  public init(id: String, name: String, description: String, count: UInt64) {
    self.id = id
    self.name = name
    self.description = description
    self.count = count
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["id", "name", "description", "count"])
    let box = try decoder.container(keyedBy: WireKey.self)
    id = try box.decode(String.self, forKey: WireKey("id"))
    name = try box.decode(String.self, forKey: WireKey("name"))
    description = try box.decode(String.self, forKey: WireKey("description"))
    count = try box.decode(UInt64.self, forKey: WireKey("count"))
  }
}

public struct StoreState: Codable, Sendable, Equatable {
  public var collections: [Collection]
  public var favorites: [ItemRef]
  public var historyCount: UInt64
  public init(collections: [Collection], favorites: [ItemRef], historyCount: UInt64) {
    self.collections = collections
    self.favorites = favorites
    self.historyCount = historyCount
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["collections", "favorites", "historyCount"])
    let box = try decoder.container(keyedBy: WireKey.self)
    collections = try box.decode([Collection].self, forKey: WireKey("collections"))
    favorites = try box.decode([ItemRef].self, forKey: WireKey("favorites"))
    historyCount = try box.decode(UInt64.self, forKey: WireKey("historyCount"))
  }
}

public struct CreatedCollection: Codable, Sendable, Equatable {
  public var collection: Collection
  public var store: StoreState
  public init(collection: Collection, store: StoreState) {
    self.collection = collection
    self.store = store
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["collection", "store"])
    let box = try decoder.container(keyedBy: WireKey.self)
    collection = try box.decode(Collection.self, forKey: WireKey("collection"))
    store = try box.decode(StoreState.self, forKey: WireKey("store"))
  }
}

public struct VolumeState: Codable, Sendable, Equatable {
  public var device: String
  public var level: Double?
  public var muted: Bool?
  public var canSetVolume: Bool
  public var canMute: Bool
  public init(
    device: String, level: Double? = nil, muted: Bool? = nil, canSetVolume: Bool, canMute: Bool
  ) {
    self.device = device
    self.level = level
    self.muted = muted
    self.canSetVolume = canSetVolume
    self.canMute = canMute
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["device", "level", "muted", "canSetVolume", "canMute"])
    let box = try decoder.container(keyedBy: WireKey.self)
    device = try box.decode(String.self, forKey: WireKey("device"))
    level = try box.decodeIfPresent(Double.self, forKey: WireKey("level"))
    muted = try box.decodeIfPresent(Bool.self, forKey: WireKey("muted"))
    canSetVolume = try box.decode(Bool.self, forKey: WireKey("canSetVolume"))
    canMute = try box.decode(Bool.self, forKey: WireKey("canMute"))
  }
}

public struct SessionState: Codable, Sendable, Equatable {
  public var authorization: Authorization
  public var canPlayCatalog: Bool?
  public init(authorization: Authorization, canPlayCatalog: Bool? = nil) {
    self.authorization = authorization
    self.canPlayCatalog = canPlayCatalog
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["authorization", "canPlayCatalog"])
    let box = try decoder.container(keyedBy: WireKey.self)
    authorization = try box.decode(Authorization.self, forKey: WireKey("authorization"))
    canPlayCatalog = try box.decodeIfPresent(Bool.self, forKey: WireKey("canPlayCatalog"))
  }
}

public struct Snapshot: Codable, Sendable, Equatable {
  public var session: SessionState
  public var player: PlayerState
  public var store: StoreState
  public var volume: VolumeState
  public init(session: SessionState, player: PlayerState, store: StoreState, volume: VolumeState) {
    self.session = session
    self.player = player
    self.store = store
    self.volume = volume
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["session", "player", "store", "volume"])
    let box = try decoder.container(keyedBy: WireKey.self)
    session = try box.decode(SessionState.self, forKey: WireKey("session"))
    player = try box.decode(PlayerState.self, forKey: WireKey("player"))
    store = try box.decode(StoreState.self, forKey: WireKey("store"))
    volume = try box.decode(VolumeState.self, forKey: WireKey("volume"))
  }
}

public struct Page: Codable, Sendable, Equatable {
  public var items: [Item]
  public var nextOffset: UInt64?
  public init(items: [Item], nextOffset: UInt64? = nil) {
    self.items = items
    self.nextOffset = nextOffset
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["items", "nextOffset"])
    let box = try decoder.container(keyedBy: WireKey.self)
    items = try box.decode([Item].self, forKey: WireKey("items"))
    nextOffset = try box.decodeIfPresent(UInt64.self, forKey: WireKey("nextOffset"))
  }
}

public struct Detail: Codable, Sendable, Equatable {
  public var item: Item
  public var children: [Item]
  public var nextOffset: UInt64?
  public init(item: Item, children: [Item], nextOffset: UInt64? = nil) {
    self.item = item
    self.children = children
    self.nextOffset = nextOffset
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["item", "children", "nextOffset"])
    let box = try decoder.container(keyedBy: WireKey.self)
    item = try box.decode(Item.self, forKey: WireKey("item"))
    children = try box.decode([Item].self, forKey: WireKey("children"))
    nextOffset = try box.decodeIfPresent(UInt64.self, forKey: WireKey("nextOffset"))
  }
}

public struct LyricLine: Codable, Sendable, Equatable {
  public var seconds: Double?
  public var text: String
  public init(seconds: Double? = nil, text: String) {
    self.seconds = seconds
    self.text = text
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["seconds", "text"])
    let box = try decoder.container(keyedBy: WireKey.self)
    seconds = try box.decodeIfPresent(Double.self, forKey: WireKey("seconds"))
    text = try box.decode(String.self, forKey: WireKey("text"))
  }
}

public struct Lyrics: Codable, Sendable, Equatable {
  public var item: ItemRef
  public var matchId: UInt64?
  public var status: LyricsStatus
  public var lines: [LyricLine]
  public var offset: Double
  public init(
    item: ItemRef, matchId: UInt64? = nil, status: LyricsStatus, lines: [LyricLine], offset: Double
  ) {
    self.item = item
    self.matchId = matchId
    self.status = status
    self.lines = lines
    self.offset = offset
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["item", "matchId", "status", "lines", "offset"])
    let box = try decoder.container(keyedBy: WireKey.self)
    item = try box.decode(ItemRef.self, forKey: WireKey("item"))
    matchId = try box.decodeIfPresent(UInt64.self, forKey: WireKey("matchId"))
    status = try box.decode(LyricsStatus.self, forKey: WireKey("status"))
    lines = try box.decode([LyricLine].self, forKey: WireKey("lines"))
    offset = try box.decode(Double.self, forKey: WireKey("offset"))
  }
}

public struct LyricMatch: Codable, Sendable, Equatable {
  public var id: UInt64
  public var title: String
  public var artist: String
  public var album: String
  public var duration: Double?
  public var synced: Bool
  public init(
    id: UInt64, title: String, artist: String, album: String, duration: Double? = nil, synced: Bool
  ) {
    self.id = id
    self.title = title
    self.artist = artist
    self.album = album
    self.duration = duration
    self.synced = synced
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["id", "title", "artist", "album", "duration", "synced"])
    let box = try decoder.container(keyedBy: WireKey.self)
    id = try box.decode(UInt64.self, forKey: WireKey("id"))
    title = try box.decode(String.self, forKey: WireKey("title"))
    artist = try box.decode(String.self, forKey: WireKey("artist"))
    album = try box.decode(String.self, forKey: WireKey("album"))
    duration = try box.decodeIfPresent(Double.self, forKey: WireKey("duration"))
    synced = try box.decode(Bool.self, forKey: WireKey("synced"))
  }
}

public struct LyricsMatches: Codable, Sendable, Equatable {
  public var item: ItemRef
  public var matches: [LyricMatch]
  public init(item: ItemRef, matches: [LyricMatch]) {
    self.item = item
    self.matches = matches
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["item", "matches"])
    let box = try decoder.container(keyedBy: WireKey.self)
    item = try box.decode(ItemRef.self, forKey: WireKey("item"))
    matches = try box.decode([LyricMatch].self, forKey: WireKey("matches"))
  }
}

public struct Artwork: Codable, Sendable, Equatable {
  public var item: ItemRef
  public var width: UInt64
  public var height: UInt64
  public var rgb: [UInt8]
  public init(item: ItemRef, width: UInt64, height: UInt64, rgb: [UInt8]) {
    self.item = item
    self.width = width
    self.height = height
    self.rgb = rgb
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["item", "width", "height", "rgb"])
    let box = try decoder.container(keyedBy: WireKey.self)
    item = try box.decode(ItemRef.self, forKey: WireKey("item"))
    width = try box.decode(UInt64.self, forKey: WireKey("width"))
    height = try box.decode(UInt64.self, forKey: WireKey("height"))
    rgb = try box.decode([UInt8].self, forKey: WireKey("rgb"))
  }
}

public struct Ack: Codable, Sendable, Equatable {
  public var message: String
  public init(message: String) {
    self.message = message
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["message"])
    let box = try decoder.container(keyedBy: WireKey.self)
    message = try box.decode(String.self, forKey: WireKey("message"))
  }
}

public struct Failure: Codable, Sendable, Equatable {
  public var code: ErrorCode
  public var message: String
  public var retryable: Bool
  public init(code: ErrorCode, message: String, retryable: Bool) {
    self.code = code
    self.message = message
    self.retryable = retryable
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["code", "message", "retryable"])
    let box = try decoder.container(keyedBy: WireKey.self)
    code = try box.decode(ErrorCode.self, forKey: WireKey("code"))
    message = try box.decode(String.self, forKey: WireKey("message"))
    retryable = try box.decode(Bool.self, forKey: WireKey("retryable"))
  }
}

public struct SearchParams: Codable, Sendable, Equatable {
  public var query: String
  public var source: Source
  public var kind: Kind
  public var offset: UInt64
  public init(query: String, source: Source, kind: Kind, offset: UInt64) {
    self.query = query
    self.source = source
    self.kind = kind
    self.offset = offset
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["query", "source", "kind", "offset"])
    let box = try decoder.container(keyedBy: WireKey.self)
    query = try box.decode(String.self, forKey: WireKey("query"))
    source = try box.decode(Source.self, forKey: WireKey("source"))
    kind = try box.decode(Kind.self, forKey: WireKey("kind"))
    offset = try box.decode(UInt64.self, forKey: WireKey("offset"))
  }
}

public struct BrowseParams: Codable, Sendable, Equatable {
  public var scope: Scope
  public var kind: Kind
  public var collectionId: String?
  public var order: Order
  public var offset: UInt64
  public init(scope: Scope, kind: Kind, collectionId: String? = nil, order: Order, offset: UInt64) {
    self.scope = scope
    self.kind = kind
    self.collectionId = collectionId
    self.order = order
    self.offset = offset
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["scope", "kind", "collectionId", "order", "offset"])
    let box = try decoder.container(keyedBy: WireKey.self)
    scope = try box.decode(Scope.self, forKey: WireKey("scope"))
    kind = try box.decode(Kind.self, forKey: WireKey("kind"))
    collectionId = try box.decodeIfPresent(String.self, forKey: WireKey("collectionId"))
    order = try box.decode(Order.self, forKey: WireKey("order"))
    offset = try box.decode(UInt64.self, forKey: WireKey("offset"))
  }
}

public struct DetailParams: Codable, Sendable, Equatable {
  public var item: ItemRef
  public var offset: UInt64
  public init(item: ItemRef, offset: UInt64) {
    self.item = item
    self.offset = offset
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["item", "offset"])
    let box = try decoder.container(keyedBy: WireKey.self)
    item = try box.decode(ItemRef.self, forKey: WireKey("item"))
    offset = try box.decode(UInt64.self, forKey: WireKey("offset"))
  }
}

public struct PlayParams: Codable, Sendable, Equatable {
  public var items: [ItemRef]
  public var startIndex: UInt64
  public var placement: Placement
  public var shuffle: Bool?
  public init(items: [ItemRef], startIndex: UInt64, placement: Placement, shuffle: Bool? = nil) {
    self.items = items
    self.startIndex = startIndex
    self.placement = placement
    self.shuffle = shuffle
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["items", "startIndex", "placement", "shuffle"])
    let box = try decoder.container(keyedBy: WireKey.self)
    items = try box.decode([ItemRef].self, forKey: WireKey("items"))
    startIndex = try box.decode(UInt64.self, forKey: WireKey("startIndex"))
    placement = try box.decode(Placement.self, forKey: WireKey("placement"))
    shuffle = try box.decodeIfPresent(Bool.self, forKey: WireKey("shuffle"))
  }
}

public struct ControlParams: Codable, Sendable, Equatable {
  public var action: Control
  public init(action: Control) {
    self.action = action
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["action"])
    let box = try decoder.container(keyedBy: WireKey.self)
    action = try box.decode(Control.self, forKey: WireKey("action"))
  }
}

public struct SeekParams: Codable, Sendable, Equatable {
  public var seconds: Double
  public var entryId: String
  public init(seconds: Double, entryId: String) {
    self.seconds = seconds
    self.entryId = entryId
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["seconds", "entryId"])
    let box = try decoder.container(keyedBy: WireKey.self)
    seconds = try box.decode(Double.self, forKey: WireKey("seconds"))
    entryId = try box.decode(String.self, forKey: WireKey("entryId"))
  }
}

public struct ModeParams: Codable, Sendable, Equatable {
  public var shuffle: Bool
  public var repeatMode: RepeatMode
  public init(shuffle: Bool, repeatMode: RepeatMode) {
    self.shuffle = shuffle
    self.repeatMode = repeatMode
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["shuffle", "repeatMode"])
    let box = try decoder.container(keyedBy: WireKey.self)
    shuffle = try box.decode(Bool.self, forKey: WireKey("shuffle"))
    repeatMode = try box.decode(RepeatMode.self, forKey: WireKey("repeatMode"))
  }
}

public struct QueueRemove: Codable, Sendable, Equatable {
  public var entryId: String
  public init(entryId: String) {
    self.entryId = entryId
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["entryId"])
    let box = try decoder.container(keyedBy: WireKey.self)
    entryId = try box.decode(String.self, forKey: WireKey("entryId"))
  }
}

public struct QueueMove: Codable, Sendable, Equatable {
  public var entryId: String
  public var beforeEntryId: String?
  public init(entryId: String, beforeEntryId: String? = nil) {
    self.entryId = entryId
    self.beforeEntryId = beforeEntryId
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["entryId", "beforeEntryId"])
    let box = try decoder.container(keyedBy: WireKey.self)
    entryId = try box.decode(String.self, forKey: WireKey("entryId"))
    beforeEntryId = try box.decodeIfPresent(String.self, forKey: WireKey("beforeEntryId"))
  }
}

public struct QueueJump: Codable, Sendable, Equatable {
  public var entryId: String
  public init(entryId: String) {
    self.entryId = entryId
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["entryId"])
    let box = try decoder.container(keyedBy: WireKey.self)
    entryId = try box.decode(String.self, forKey: WireKey("entryId"))
  }
}

public struct CollectionCreate: Codable, Sendable, Equatable {
  public var name: String
  public var description: String
  public var items: [ItemRef]?
  public init(name: String, description: String, items: [ItemRef]? = nil) {
    self.name = name
    self.description = description
    self.items = items
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["name", "description", "items"])
    let box = try decoder.container(keyedBy: WireKey.self)
    name = try box.decode(String.self, forKey: WireKey("name"))
    description = try box.decode(String.self, forKey: WireKey("description"))
    items = try box.decodeIfPresent([ItemRef].self, forKey: WireKey("items"))
  }
}

public struct CollectionUpdate: Codable, Sendable, Equatable {
  public var id: String
  public var name: String?
  public var description: String?
  public init(id: String, name: String? = nil, description: String? = nil) {
    self.id = id
    self.name = name
    self.description = description
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["id", "name", "description"])
    let box = try decoder.container(keyedBy: WireKey.self)
    id = try box.decode(String.self, forKey: WireKey("id"))
    name = try box.decodeIfPresent(String.self, forKey: WireKey("name"))
    description = try box.decodeIfPresent(String.self, forKey: WireKey("description"))
  }
}

public struct CollectionDelete: Codable, Sendable, Equatable {
  public var id: String
  public init(id: String) {
    self.id = id
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["id"])
    let box = try decoder.container(keyedBy: WireKey.self)
    id = try box.decode(String.self, forKey: WireKey("id"))
  }
}

public struct CollectionAdd: Codable, Sendable, Equatable {
  public var id: String
  public var items: [ItemRef]
  public init(id: String, items: [ItemRef]) {
    self.id = id
    self.items = items
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["id", "items"])
    let box = try decoder.container(keyedBy: WireKey.self)
    id = try box.decode(String.self, forKey: WireKey("id"))
    items = try box.decode([ItemRef].self, forKey: WireKey("items"))
  }
}

public struct CollectionRemove: Codable, Sendable, Equatable {
  public var id: String
  public var index: UInt64
  public init(id: String, index: UInt64) {
    self.id = id
    self.index = index
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["id", "index"])
    let box = try decoder.container(keyedBy: WireKey.self)
    id = try box.decode(String.self, forKey: WireKey("id"))
    index = try box.decode(UInt64.self, forKey: WireKey("index"))
  }
}

public struct CollectionMove: Codable, Sendable, Equatable {
  public var id: String
  public var from: UInt64
  public var to: UInt64
  public init(id: String, from: UInt64, to: UInt64) {
    self.id = id
    self.from = from
    self.to = to
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["id", "from", "to"])
    let box = try decoder.container(keyedBy: WireKey.self)
    id = try box.decode(String.self, forKey: WireKey("id"))
    from = try box.decode(UInt64.self, forKey: WireKey("from"))
    to = try box.decode(UInt64.self, forKey: WireKey("to"))
  }
}

public struct CollectionCopy: Codable, Sendable, Equatable {
  public var item: ItemRef
  public var name: String
  public init(item: ItemRef, name: String) {
    self.item = item
    self.name = name
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["item", "name"])
    let box = try decoder.container(keyedBy: WireKey.self)
    item = try box.decode(ItemRef.self, forKey: WireKey("item"))
    name = try box.decode(String.self, forKey: WireKey("name"))
  }
}

public struct FavoriteParams: Codable, Sendable, Equatable {
  public var item: ItemRef
  public var enabled: Bool
  public init(item: ItemRef, enabled: Bool) {
    self.item = item
    self.enabled = enabled
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["item", "enabled"])
    let box = try decoder.container(keyedBy: WireKey.self)
    item = try box.decode(ItemRef.self, forKey: WireKey("item"))
    enabled = try box.decode(Bool.self, forKey: WireKey("enabled"))
  }
}

public struct LyricsParams: Codable, Sendable, Equatable {
  public var item: ItemRef
  public init(item: ItemRef) {
    self.item = item
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["item"])
    let box = try decoder.container(keyedBy: WireKey.self)
    item = try box.decode(ItemRef.self, forKey: WireKey("item"))
  }
}

public struct LyricsSearchParams: Codable, Sendable, Equatable {
  public var item: ItemRef
  public var query: String
  public init(item: ItemRef, query: String) {
    self.item = item
    self.query = query
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["item", "query"])
    let box = try decoder.container(keyedBy: WireKey.self)
    item = try box.decode(ItemRef.self, forKey: WireKey("item"))
    query = try box.decode(String.self, forKey: WireKey("query"))
  }
}

public struct LyricsChooseParams: Codable, Sendable, Equatable {
  public var item: ItemRef
  public var matchId: UInt64
  public init(item: ItemRef, matchId: UInt64) {
    self.item = item
    self.matchId = matchId
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["item", "matchId"])
    let box = try decoder.container(keyedBy: WireKey.self)
    item = try box.decode(ItemRef.self, forKey: WireKey("item"))
    matchId = try box.decode(UInt64.self, forKey: WireKey("matchId"))
  }
}

public struct LyricsOffsetParams: Codable, Sendable, Equatable {
  public var item: ItemRef
  public var seconds: Double
  public init(item: ItemRef, seconds: Double) {
    self.item = item
    self.seconds = seconds
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["item", "seconds"])
    let box = try decoder.container(keyedBy: WireKey.self)
    item = try box.decode(ItemRef.self, forKey: WireKey("item"))
    seconds = try box.decode(Double.self, forKey: WireKey("seconds"))
  }
}

public struct VolumeParams: Codable, Sendable, Equatable {
  public var level: Double?
  public var muted: Bool?
  public init(level: Double? = nil, muted: Bool? = nil) {
    self.level = level
    self.muted = muted
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["level", "muted"])
    let box = try decoder.container(keyedBy: WireKey.self)
    level = try box.decodeIfPresent(Double.self, forKey: WireKey("level"))
    muted = try box.decodeIfPresent(Bool.self, forKey: WireKey("muted"))
  }
}

public struct ArtworkParams: Codable, Sendable, Equatable {
  public var item: ItemRef
  public init(item: ItemRef) {
    self.item = item
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["item"])
    let box = try decoder.container(keyedBy: WireKey.self)
    item = try box.decode(ItemRef.self, forKey: WireKey("item"))
  }
}

public struct CancelParams: Codable, Sendable, Equatable {
  public var requestId: UInt64
  public init(requestId: UInt64) {
    self.requestId = requestId
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["requestId"])
    let box = try decoder.container(keyedBy: WireKey.self)
    requestId = try box.decode(UInt64.self, forKey: WireKey("requestId"))
  }
}

public struct Request: Codable, Sendable, Equatable {
  public var version: UInt64
  public var id: UInt64
  public var command: Command
  public init(version: UInt64, id: UInt64, command: Command) {
    self.version = version
    self.id = id
    self.command = command
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["version", "id", "command"])
    let box = try decoder.container(keyedBy: WireKey.self)
    version = try box.decode(UInt64.self, forKey: WireKey("version"))
    id = try box.decode(UInt64.self, forKey: WireKey("id"))
    command = try box.decode(Command.self, forKey: WireKey("command"))
  }
}

public struct Event: Codable, Sendable, Equatable {
  public var version: UInt64
  public var id: UInt64?
  public var sequence: UInt64
  public var event: Notice
  public init(version: UInt64, id: UInt64? = nil, sequence: UInt64, event: Notice) {
    self.version = version
    self.id = id
    self.sequence = sequence
    self.event = event
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["version", "id", "sequence", "event"])
    let box = try decoder.container(keyedBy: WireKey.self)
    version = try box.decode(UInt64.self, forKey: WireKey("version"))
    id = try box.decodeIfPresent(UInt64.self, forKey: WireKey("id"))
    sequence = try box.decode(UInt64.self, forKey: WireKey("sequence"))
    event = try box.decode(Notice.self, forKey: WireKey("event"))
  }
}

public enum Command: Codable, Sendable, Equatable {
  case snapshot(Empty)
  case authorize(Empty)
  case search(SearchParams)
  case browse(BrowseParams)
  case detail(DetailParams)
  case play(PlayParams)
  case control(ControlParams)
  case seek(SeekParams)
  case mode(ModeParams)
  case queue(QueueParams)
  case queueRemove(QueueRemove)
  case queueMove(QueueMove)
  case queueJump(QueueJump)
  case queueClear(Empty)
  case collectionCreate(CollectionCreate)
  case collectionUpdate(CollectionUpdate)
  case collectionDelete(CollectionDelete)
  case collectionAdd(CollectionAdd)
  case collectionRemove(CollectionRemove)
  case collectionMove(CollectionMove)
  case collectionCopy(CollectionCopy)
  case favorite(FavoriteParams)
  case lyrics(LyricsParams)
  case lyricsSearch(LyricsSearchParams)
  case lyricsChoose(LyricsChooseParams)
  case lyricsOffset(LyricsOffsetParams)
  case volume(VolumeParams)
  case artwork(ArtworkParams)
  case cancel(CancelParams)
  public var tag: String {
    switch self {
    case .snapshot: "snapshot"
    case .authorize: "authorize"
    case .search: "search"
    case .browse: "browse"
    case .detail: "detail"
    case .play: "play"
    case .control: "control"
    case .seek: "seek"
    case .mode: "mode"
    case .queue: "queue"
    case .queueRemove: "queue_remove"
    case .queueMove: "queue_move"
    case .queueJump: "queue_jump"
    case .queueClear: "queue_clear"
    case .collectionCreate: "collection_create"
    case .collectionUpdate: "collection_update"
    case .collectionDelete: "collection_delete"
    case .collectionAdd: "collection_add"
    case .collectionRemove: "collection_remove"
    case .collectionMove: "collection_move"
    case .collectionCopy: "collection_copy"
    case .favorite: "favorite"
    case .lyrics: "lyrics"
    case .lyricsSearch: "lyrics_search"
    case .lyricsChoose: "lyrics_choose"
    case .lyricsOffset: "lyrics_offset"
    case .volume: "volume"
    case .artwork: "artwork"
    case .cancel: "cancel"
    }
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["type", "data"])
    let box = try decoder.container(keyedBy: WireKey.self)
    switch try box.decode(String.self, forKey: WireKey("type")) {
    case "snapshot": self = .snapshot(try box.decode(Empty.self, forKey: WireKey("data")))
    case "authorize": self = .authorize(try box.decode(Empty.self, forKey: WireKey("data")))
    case "search": self = .search(try box.decode(SearchParams.self, forKey: WireKey("data")))
    case "browse": self = .browse(try box.decode(BrowseParams.self, forKey: WireKey("data")))
    case "detail": self = .detail(try box.decode(DetailParams.self, forKey: WireKey("data")))
    case "play": self = .play(try box.decode(PlayParams.self, forKey: WireKey("data")))
    case "control": self = .control(try box.decode(ControlParams.self, forKey: WireKey("data")))
    case "seek": self = .seek(try box.decode(SeekParams.self, forKey: WireKey("data")))
    case "mode": self = .mode(try box.decode(ModeParams.self, forKey: WireKey("data")))
    case "queue": self = .queue(try box.decode(QueueParams.self, forKey: WireKey("data")))
    case "queue_remove":
      self = .queueRemove(try box.decode(QueueRemove.self, forKey: WireKey("data")))
    case "queue_move": self = .queueMove(try box.decode(QueueMove.self, forKey: WireKey("data")))
    case "queue_jump": self = .queueJump(try box.decode(QueueJump.self, forKey: WireKey("data")))
    case "queue_clear": self = .queueClear(try box.decode(Empty.self, forKey: WireKey("data")))
    case "collection_create":
      self = .collectionCreate(try box.decode(CollectionCreate.self, forKey: WireKey("data")))
    case "collection_update":
      self = .collectionUpdate(try box.decode(CollectionUpdate.self, forKey: WireKey("data")))
    case "collection_delete":
      self = .collectionDelete(try box.decode(CollectionDelete.self, forKey: WireKey("data")))
    case "collection_add":
      self = .collectionAdd(try box.decode(CollectionAdd.self, forKey: WireKey("data")))
    case "collection_remove":
      self = .collectionRemove(try box.decode(CollectionRemove.self, forKey: WireKey("data")))
    case "collection_move":
      self = .collectionMove(try box.decode(CollectionMove.self, forKey: WireKey("data")))
    case "collection_copy":
      self = .collectionCopy(try box.decode(CollectionCopy.self, forKey: WireKey("data")))
    case "favorite": self = .favorite(try box.decode(FavoriteParams.self, forKey: WireKey("data")))
    case "lyrics": self = .lyrics(try box.decode(LyricsParams.self, forKey: WireKey("data")))
    case "lyrics_search":
      self = .lyricsSearch(try box.decode(LyricsSearchParams.self, forKey: WireKey("data")))
    case "lyrics_choose":
      self = .lyricsChoose(try box.decode(LyricsChooseParams.self, forKey: WireKey("data")))
    case "lyrics_offset":
      self = .lyricsOffset(try box.decode(LyricsOffsetParams.self, forKey: WireKey("data")))
    case "volume": self = .volume(try box.decode(VolumeParams.self, forKey: WireKey("data")))
    case "artwork": self = .artwork(try box.decode(ArtworkParams.self, forKey: WireKey("data")))
    case "cancel": self = .cancel(try box.decode(CancelParams.self, forKey: WireKey("data")))
    default:
      throw DecodingError.dataCorrupted(
        .init(codingPath: decoder.codingPath, debugDescription: "Unknown message type"))
    }
  }
  public func encode(to encoder: Encoder) throws {
    var box = encoder.container(keyedBy: WireKey.self)
    switch self {
    case .snapshot(let value):
      try box.encode("snapshot", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .authorize(let value):
      try box.encode("authorize", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .search(let value):
      try box.encode("search", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .browse(let value):
      try box.encode("browse", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .detail(let value):
      try box.encode("detail", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .play(let value):
      try box.encode("play", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .control(let value):
      try box.encode("control", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .seek(let value):
      try box.encode("seek", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .mode(let value):
      try box.encode("mode", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .queue(let value):
      try box.encode("queue", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .queueRemove(let value):
      try box.encode("queue_remove", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .queueMove(let value):
      try box.encode("queue_move", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .queueJump(let value):
      try box.encode("queue_jump", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .queueClear(let value):
      try box.encode("queue_clear", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .collectionCreate(let value):
      try box.encode("collection_create", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .collectionUpdate(let value):
      try box.encode("collection_update", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .collectionDelete(let value):
      try box.encode("collection_delete", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .collectionAdd(let value):
      try box.encode("collection_add", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .collectionRemove(let value):
      try box.encode("collection_remove", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .collectionMove(let value):
      try box.encode("collection_move", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .collectionCopy(let value):
      try box.encode("collection_copy", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .favorite(let value):
      try box.encode("favorite", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .lyrics(let value):
      try box.encode("lyrics", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .lyricsSearch(let value):
      try box.encode("lyrics_search", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .lyricsChoose(let value):
      try box.encode("lyrics_choose", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .lyricsOffset(let value):
      try box.encode("lyrics_offset", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .volume(let value):
      try box.encode("volume", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .artwork(let value):
      try box.encode("artwork", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .cancel(let value):
      try box.encode("cancel", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    }
  }
}

public enum Notice: Codable, Sendable, Equatable {
  case snapshot(Snapshot)
  case session(SessionState)
  case page(Page)
  case detail(Detail)
  case player(PlayerState)
  case queue(QueuePage)
  case store(StoreState)
  case collectionCreated(CreatedCollection)
  case lyrics(Lyrics)
  case lyricsMatches(LyricsMatches)
  case volume(VolumeState)
  case artwork(Artwork)
  case ack(Ack)
  case failure(Failure)
  public var tag: String {
    switch self {
    case .snapshot: "snapshot"
    case .session: "session"
    case .page: "page"
    case .detail: "detail"
    case .player: "player"
    case .queue: "queue"
    case .store: "store"
    case .collectionCreated: "collection_created"
    case .lyrics: "lyrics"
    case .lyricsMatches: "lyrics_matches"
    case .volume: "volume"
    case .artwork: "artwork"
    case .ack: "ack"
    case .failure: "failure"
    }
  }
  public init(from decoder: Decoder) throws {
    try checkKeys(decoder, ["type", "data"])
    let box = try decoder.container(keyedBy: WireKey.self)
    switch try box.decode(String.self, forKey: WireKey("type")) {
    case "snapshot": self = .snapshot(try box.decode(Snapshot.self, forKey: WireKey("data")))
    case "session": self = .session(try box.decode(SessionState.self, forKey: WireKey("data")))
    case "page": self = .page(try box.decode(Page.self, forKey: WireKey("data")))
    case "detail": self = .detail(try box.decode(Detail.self, forKey: WireKey("data")))
    case "player": self = .player(try box.decode(PlayerState.self, forKey: WireKey("data")))
    case "queue": self = .queue(try box.decode(QueuePage.self, forKey: WireKey("data")))
    case "store": self = .store(try box.decode(StoreState.self, forKey: WireKey("data")))
    case "collection_created":
      self = .collectionCreated(try box.decode(CreatedCollection.self, forKey: WireKey("data")))
    case "lyrics": self = .lyrics(try box.decode(Lyrics.self, forKey: WireKey("data")))
    case "lyrics_matches":
      self = .lyricsMatches(try box.decode(LyricsMatches.self, forKey: WireKey("data")))
    case "volume": self = .volume(try box.decode(VolumeState.self, forKey: WireKey("data")))
    case "artwork": self = .artwork(try box.decode(Artwork.self, forKey: WireKey("data")))
    case "ack": self = .ack(try box.decode(Ack.self, forKey: WireKey("data")))
    case "failure": self = .failure(try box.decode(Failure.self, forKey: WireKey("data")))
    default:
      throw DecodingError.dataCorrupted(
        .init(codingPath: decoder.codingPath, debugDescription: "Unknown message type"))
    }
  }
  public func encode(to encoder: Encoder) throws {
    var box = encoder.container(keyedBy: WireKey.self)
    switch self {
    case .snapshot(let value):
      try box.encode("snapshot", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .session(let value):
      try box.encode("session", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .page(let value):
      try box.encode("page", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .detail(let value):
      try box.encode("detail", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .player(let value):
      try box.encode("player", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .queue(let value):
      try box.encode("queue", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .store(let value):
      try box.encode("store", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .collectionCreated(let value):
      try box.encode("collection_created", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .lyrics(let value):
      try box.encode("lyrics", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .lyricsMatches(let value):
      try box.encode("lyrics_matches", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .volume(let value):
      try box.encode("volume", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .artwork(let value):
      try box.encode("artwork", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .ack(let value):
      try box.encode("ack", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    case .failure(let value):
      try box.encode("failure", forKey: WireKey("type"))
      try box.encode(value, forKey: WireKey("data"))
    }
  }
}
