use crate::{generate::write_generated, process::Result};
use base64::{Engine, engine::general_purpose::STANDARD};
use flate2::{Compression, write::DeflateEncoder};
use serde_json::{Value, json};
use std::{collections::HashMap, fs, io::Write};

fn reference(kind: &str, index: usize) -> Value {
    json!({"source":"library", "kind":kind, "id":format!("fixture-{kind}-{index}")})
}

pub fn corpus() -> Result<Value> {
    let source: Value = serde_json::from_slice(&fs::read("backend/Fixtures/demo.json")?)?;
    let mut tracks = Vec::new();
    let mut albums = Vec::new();
    let mut album_ids = HashMap::new();
    for (index, song) in source["tracks"]
        .as_array()
        .ok_or("Missing demo tracks")?
        .iter()
        .enumerate()
    {
        let key = (
            song["artist"].as_str().ok_or("Missing demo artist")?,
            song["album"].as_str().ok_or("Missing demo album")?,
        );
        let next = album_ids.len();
        let album = *album_ids.entry(key).or_insert(next);
        let mut item = song.clone();
        item["ref"] = reference("song", index);
        item["albumRef"] = reference("album", album);
        item["artistRef"] = reference("artist", album);
        if index == 0 {
            item["artworkUrl"] = json!("demo://cover");
        }
        tracks.push(item.clone());
        if album == albums.len() {
            item["ref"] = reference("album", album);
            item["title"] = song["album"].clone();
            albums.push(item);
        }
    }
    let select = |indices: &Value| -> Result<Vec<Value>> {
        indices
            .as_array()
            .ok_or("Missing demo selection")?
            .iter()
            .map(|index| {
                let index = index.as_u64().ok_or("Invalid demo index")? as usize;
                tracks
                    .get(index)
                    .cloned()
                    .ok_or_else(|| "Demo index out of bounds".into())
            })
            .collect()
    };
    let queue: Vec<_> = select(&source["queue"])?
        .into_iter()
        .enumerate()
        .map(|(i, item)| json!({"id":format!("queue-{i}"), "item":item}))
        .collect();
    let mut cover = Vec::with_capacity(96 * 96 * 3);
    for y in 0..96 {
        for x in 0..96 {
            let ridge = (x as f64 - 47.5).abs() + (y as f64 - 47.5).abs() * 0.55;
            let (a, b) = if ridge < 26.0 {
                ([225.0, 113.0, 144.0], [250.0, 211.0, 168.0])
            } else {
                ([18.0, 24.0, 43.0], [225.0, 113.0, 144.0])
            };
            let blend = ((y as f64 + x as f64 * 0.28) / 122.0).min(1.0);
            cover.extend(
                a.into_iter()
                    .zip(b)
                    .map(|(left, right)| (left + (right - left) * blend).round_ties_even() as u8),
            );
        }
    }
    Ok(json!({
        "tracks":tracks,"albums":albums,"lyrics":source["lyrics"],
        "seed":{"version":1,"collections":[{"id":"evening","name":source["playlist"]["name"],"description":"","items":select(&source["playlist"]["tracks"])?}],
            "favorites":select(&source["favorites"] )?,"history":select(&source["history"] )?,"lyrics":{}},
        "player":{"current":tracks.first().ok_or("Empty demo")?,"playing":true,"position":12.0,"updatedAt":1000.0,"queueCount":queue.len(),"queueRevision":1,"currentEntryId":"playing","repeatMode":"off","shuffle":false,"canSeek":true},
        "volume":{"device":"Demo","level":0.65,"muted":false,"canSetVolume":true,"canMute":true},
        "queue":queue,"cover":cover
    }))
}

pub fn generate(check: bool) -> Result {
    let mut compressor = DeflateEncoder::new(Vec::new(), Compression::best());
    compressor.write_all(&serde_json::to_vec(&corpus()?)?)?;
    let encoded = STANDARD.encode(compressor.finish()?);
    let lines: Vec<_> = encoded
        .as_bytes()
        .chunks(76)
        .map(|s| format!("    {}", std::str::from_utf8(s).unwrap()))
        .collect();
    let output = format!(
        "// Generated by cargo xtask demo; do not edit. Explicit demo mode only.\nenum DemoAssets {{\n  static let payload = \"\"\"\n{}\n    \"\"\"\n}}\n",
        lines.join("\n")
    );
    write_generated(
        "backend/Sources/Backend/DemoAssets.generated.swift",
        output.as_bytes(),
        check,
    )?;
    println!("Embedded demo corpus verified");
    Ok(())
}
