use crate::process::{Result, ensure, filter};
use regex::Regex;
use serde_json::{Map, Value, json};
use std::{collections::HashSet, fmt::Write as _, fs, process::Command};

const PRIMITIVES: &[(&str, &str)] = &[
    ("String", "String"),
    ("Bool", "bool"),
    ("UInt64", "u64"),
    ("UInt8", "u8"),
    ("Double", "f64"),
];

fn text(value: &Value) -> &str {
    value.as_str().expect("Expected schema string")
}
fn object(value: &Value) -> &Map<String, Value> {
    value.as_object().expect("Expected schema object")
}
fn snake(name: &str) -> String {
    let mut value = String::new();
    for (index, c) in name.chars().enumerate() {
        if index > 0 && c.is_ascii_uppercase() {
            value.push('_');
        }
        value.push(c.to_ascii_lowercase());
    }
    value
}
fn camel(name: &str) -> String {
    let mut parts = name.split('_');
    let mut value = parts.next().unwrap().to_owned();
    for part in parts {
        let mut chars = part.chars();
        if let Some(c) = chars.next() {
            value.push(c.to_ascii_uppercase());
        }
        value.extend(chars);
    }
    value
}
fn pascal(name: &str) -> String {
    let value = camel(name);
    value[..1].to_ascii_uppercase() + &value[1..]
}
fn native(kind: &str, rust: bool) -> String {
    if let Some(inner) = kind.strip_suffix('?') {
        let inner = native(inner, rust);
        return if rust {
            format!("Option<{inner}>")
        } else {
            format!("{inner}?")
        };
    }
    if let Some(inner) = kind.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
        let inner = native(inner, rust);
        return if rust {
            format!("Vec<{inner}>")
        } else {
            format!("[{inner}]")
        };
    }
    if rust {
        PRIMITIVES
            .iter()
            .find(|(swift, _)| *swift == kind)
            .map(|(_, rust)| *rust)
            .unwrap_or(kind)
            .into()
    } else {
        kind.into()
    }
}

fn validate(spec: &Value) -> Result {
    let mut names: HashSet<&str> = PRIMITIVES.iter().map(|(name, _)| *name).collect();
    let type_name = Regex::new(r"^[A-Z][A-Za-z0-9]*$")?;
    let field_name = Regex::new(r"^[a-z][A-Za-z0-9_]*$")?;
    for group in ["enums", "records", "unions"] {
        for name in object(&spec[group]).keys() {
            ensure(
                type_name.is_match(name) && names.insert(name),
                "Invalid or duplicate schema type",
            )?;
        }
    }
    for group in ["records", "unions"] {
        for fields in object(&spec[group]).values() {
            for (key, kind) in object(fields) {
                ensure(
                    field_name.is_match(key)
                        && names.contains(text(kind).trim_matches(['[', ']', '?'])),
                    "Invalid field name or type",
                )?;
            }
        }
    }
    ensure(
        spec["version"].as_u64().is_some() && spec["maxMessageBytes"] == 1_048_576,
        "Invalid protocol bounds",
    )
}

fn swift(spec: &Value) -> String {
    let mut out = format!(
        "// Generated by cargo xtask generate. Do not edit.\nimport Foundation\n\npublic let apiVersion: UInt64 = {}\npublic let maxMessageBytes = {}\n\n",
        spec["version"], spec["maxMessageBytes"]
    );
    out.push_str(r#"private struct WireKey: CodingKey {
  let stringValue: String
  var intValue: Int? { nil }
  init(_ value: String) { stringValue = value }
  init?(stringValue: String) { self.init(stringValue) }
  init?(intValue: Int) { return nil }
}

private func checkKeys(_ decoder: Decoder, _ allowed: Set<String>) throws {
  let box = try decoder.container(keyedBy: WireKey.self)
  guard Set(box.allKeys.map(\.stringValue)).isSubset(of: allowed) else {
    throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: "Unknown field"))
  }
}

"#);
    for (name, values) in object(&spec["enums"]) {
        writeln!(
            out,
            "public enum {name}: String, Codable, Sendable, CaseIterable {{"
        )
        .unwrap();
        for value in values.as_array().unwrap() {
            writeln!(out, "  case {} = {value}", camel(text(value))).unwrap();
        }
        out.push_str("}\n\n");
    }
    for (name, fields) in object(&spec["records"]) {
        let fields = object(fields);
        writeln!(out, "public struct {name}: Codable, Sendable, Equatable {{").unwrap();
        for (key, kind) in fields {
            writeln!(out, "  public var {key}: {}", native(text(kind), false)).unwrap();
        }
        let params: Vec<_> = fields
            .iter()
            .map(|(key, kind)| {
                format!(
                    "{key}: {}{}",
                    native(text(kind), false),
                    if text(kind).ends_with('?') {
                        " = nil"
                    } else {
                        ""
                    }
                )
            })
            .collect();
        writeln!(out, "  public init({}) {{", params.join(", ")).unwrap();
        for key in fields.keys() {
            writeln!(out, "    self.{key} = {key}").unwrap();
        }
        out.push_str("  }\n  public init(from decoder: Decoder) throws {\n");
        let keys: Vec<_> = fields.keys().map(|k| format!("\"{k}\"")).collect();
        writeln!(out, "    try checkKeys(decoder, [{}])", keys.join(", ")).unwrap();
        if !fields.is_empty() {
            out.push_str("    let box = try decoder.container(keyedBy: WireKey.self)\n");
        }
        for (key, kind) in fields {
            let kind = text(kind);
            let method = if kind.ends_with('?') {
                "decodeIfPresent"
            } else {
                "decode"
            };
            writeln!(
                out,
                "    {key} = try box.{method}({}.self, forKey: WireKey(\"{key}\"))",
                native(kind.trim_end_matches('?'), false)
            )
            .unwrap();
        }
        out.push_str("  }\n}\n\n");
    }
    for (name, variants) in object(&spec["unions"]) {
        let variants = object(variants);
        writeln!(out, "public enum {name}: Codable, Sendable, Equatable {{").unwrap();
        for (tag, kind) in variants {
            writeln!(out, "  case {}({})", camel(tag), text(kind)).unwrap();
        }
        out.push_str("  public var tag: String {\n    switch self {\n");
        for tag in variants.keys() {
            writeln!(out, "    case .{}: \"{tag}\"", camel(tag)).unwrap();
        }
        out.push_str("    }\n  }\n  public init(from decoder: Decoder) throws {\n    try checkKeys(decoder, [\"type\", \"data\"])\n    let box = try decoder.container(keyedBy: WireKey.self)\n    switch try box.decode(String.self, forKey: WireKey(\"type\")) {\n");
        for (tag, kind) in variants {
            writeln!(out, "    case \"{tag}\": self = .{}(try box.decode({}.self, forKey: WireKey(\"data\")))", camel(tag), text(kind)).unwrap();
        }
        out.push_str("    default: throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: \"Unknown message type\"))\n    }\n  }\n  public func encode(to encoder: Encoder) throws {\n    var box = encoder.container(keyedBy: WireKey.self)\n    switch self {\n");
        for tag in variants.keys() {
            writeln!(out, "    case .{}(let value):\n      try box.encode(\"{tag}\", forKey: WireKey(\"type\"))\n      try box.encode(value, forKey: WireKey(\"data\"))", camel(tag)).unwrap();
        }
        out.push_str("    }\n  }\n}\n\n");
    }
    out
}

fn rust(spec: &Value) -> String {
    let mut out = format!(
        "// Generated by cargo xtask generate. Do not edit.\nuse serde::{{Deserialize, Serialize}};\npub const API_VERSION: u64 = {};\npub const MAX_MESSAGE_BYTES: usize = {};\n\n",
        spec["version"], spec["maxMessageBytes"]
    );
    for (name, values) in object(&spec["enums"]) {
        writeln!(out, "#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]\n#[serde(rename_all = \"snake_case\")]\npub enum {name} {{").unwrap();
        for value in values.as_array().unwrap() {
            writeln!(out, "    {},", pascal(text(value))).unwrap();
        }
        out.push_str("}\n\n");
    }
    for (name, fields) in object(&spec["records"]) {
        writeln!(out, "#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]\n#[serde(rename_all = \"camelCase\", deny_unknown_fields)]\npub struct {name} {{").unwrap();
        for (key, kind) in object(fields) {
            if text(kind).ends_with('?') {
                out.push_str("#[serde(skip_serializing_if = \"Option::is_none\")]\n");
            }
            let key = if key == "ref" {
                "r#ref".into()
            } else {
                snake(key)
            };
            writeln!(out, "pub {key}: {},", native(text(kind), true)).unwrap();
        }
        out.push_str("}\n\n");
    }
    for (name, variants) in object(&spec["unions"]) {
        writeln!(out, "#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]\n#[serde(tag = \"type\", content = \"data\", rename_all = \"snake_case\", deny_unknown_fields)]\npub enum {name} {{").unwrap();
        for (tag, kind) in object(variants) {
            writeln!(out, "    {}({}),", pascal(tag), text(kind)).unwrap();
        }
        out.push_str("}\n\n");
    }
    out
}

fn json_type(kind: &str) -> Value {
    if let Some(inner) = kind.strip_suffix('?') {
        return json!({"anyOf":[json_type(inner), {"type":"null"}]});
    }
    if let Some(inner) = kind.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
        return json!({"type":"array","items":json_type(inner),"maxItems":32768});
    }
    match kind {
        "String" => json!({"type":"string","maxLength":8192}),
        "Bool" => json!({"type":"boolean"}),
        "UInt64" => json!({"type":"integer","minimum":0,"maximum":u64::MAX}),
        "UInt8" => json!({"type":"integer","minimum":0,"maximum":255}),
        "Double" => json!({"type":"number"}),
        _ => json!({"$ref":format!("#/$defs/{kind}")}),
    }
}

fn schema(spec: &Value) -> Value {
    let mut definitions = Map::new();
    for (name, values) in object(&spec["enums"]) {
        definitions.insert(name.clone(), json!({"type":"string","enum":values}));
    }
    for (name, fields) in object(&spec["records"]) {
        let fields = object(fields);
        let mut props = Value::Object(
            fields
                .iter()
                .map(|(key, kind)| (key.clone(), json_type(text(kind))))
                .collect(),
        );
        if ["Request", "Event"].contains(&name.as_str()) {
            props["version"] = json!({"const":spec["version"]});
        }
        if name == "Request" {
            props["id"]["minimum"] = json!(1);
        }
        if name == "Event" {
            props["sequence"]["minimum"] = json!(1);
            props["id"]["anyOf"][0]["minimum"] = json!(1);
        }
        let required: Vec<_> = fields
            .iter()
            .filter(|(_, kind)| !text(kind).ends_with('?'))
            .map(|(key, _)| key)
            .collect();
        definitions.insert(name.clone(),json!({"type":"object","additionalProperties":false,"properties":props,"required":required}));
    }
    for (name, variants) in object(&spec["unions"]) {
        let variants: Vec<_> = object(variants).iter().map(|(tag,kind)| json!({"type":"object","additionalProperties":false,"properties":{"type":{"const":tag},"data":json_type(text(kind))},"required":["type","data"]})).collect();
        definitions.insert(name.clone(), json!({"oneOf":variants}));
    }
    json!({"$schema":"https://json-schema.org/draft/2020-12/schema","title":"Music backend API v1","oneOf":[{"$ref":"#/$defs/Request"},{"$ref":"#/$defs/Event"}],"$defs":definitions})
}

pub fn write_generated(path: &str, bytes: &[u8], check: bool) -> Result {
    if check {
        ensure(
            fs::read(path)?.as_slice() == bytes,
            &format!("Stale generated file: {path}"),
        )
    } else {
        fs::write(path, bytes)?;
        Ok(())
    }
}

pub fn generate(check: bool) -> Result {
    let spec: Value = serde_json::from_slice(&fs::read("contract/api.json")?)?;
    validate(&spec)?;
    let swift = filter(
        Command::new("swift").args(["format", "format", "-"]),
        swift(&spec).as_bytes(),
    )?;
    let rust = filter(
        Command::new("rustfmt").args(["--edition", "2024"]),
        rust(&spec).as_bytes(),
    )?;
    write_generated(
        "backend/Sources/MusicContract/Generated.swift",
        &swift,
        check,
    )?;
    write_generated("frontend/src/generated.rs", &rust, check)?;
    write_generated(
        "contract/schema.json",
        format!("{}\n", serde_json::to_string_pretty(&schema(&spec))?).as_bytes(),
        check,
    )?;
    println!("Contract generation verified");
    Ok(())
}
