#[derive(Clone, Copy)]
pub enum Icon {
    Music,
    Headphones,
    Search,
    Home,
    Clock,
    Artist,
    Album,
    Songs,
    Playlist,
    Heart,
    HeartEmpty,
    History,
    Play,
    Pause,
    Previous,
    Next,
    Shuffle,
    Repeat,
    Volume,
    Mute,
    Lyrics,
    Theme,
    Transparent,
    Settings,
    Help,
    Keyboard,
    Check,
    Sidebar,
    ClosePanel,
    OpenPanel,
    Chevron,
    CapLeft,
    CapRight,
}

impl Icon {
    pub fn glyph(self, plain: bool) -> &'static str {
        let (nerd, fallback) = match self {
            Self::Music | Self::Songs => ("\u{f001}", "♫"),
            Self::Headphones => ("\u{f025}", "♫"),
            Self::Search => ("\u{f002}", "/"),
            Self::Home => ("\u{f015}", "⌂"),
            Self::Clock => ("\u{f017}", "◷"),
            Self::Artist => ("\u{f0c0}", "♩"),
            Self::Album => ("\u{f192}", "▣"),
            Self::Playlist => ("\u{f03a}", "≡"),
            Self::Heart => ("\u{f004}", "♥"),
            Self::HeartEmpty => ("\u{f08a}", "♡"),
            Self::History => ("\u{f1da}", "◷"),
            Self::Play => ("\u{f04b}", "▶"),
            Self::Pause => ("\u{f04c}", "Ⅱ"),
            Self::Previous => ("\u{f048}", "‹"),
            Self::Next => ("\u{f051}", "›"),
            Self::Shuffle => ("\u{f074}", "⤨"),
            Self::Repeat => ("\u{f01e}", "↻"),
            Self::Volume => ("\u{f028}", "♪"),
            Self::Mute => ("\u{f026}", "×"),
            Self::Lyrics => ("\u{f27a}", "≋"),
            Self::Theme => ("\u{f1fc}", "◐"),
            Self::Transparent => ("\u{f042}", "◐"),
            Self::Settings => ("\u{f013}", "⚙"),
            Self::Help => ("\u{f059}", "?"),
            Self::Keyboard => ("\u{f11c}", "⌨"),
            Self::Check => ("\u{f00c}", "✓"),
            Self::Sidebar => ("\u{f0db}", "≡"),
            Self::ClosePanel => ("\u{f03b}", "‹"),
            Self::OpenPanel => ("\u{f03c}", "›"),
            Self::Chevron => ("\u{f105}", "›"),
            Self::CapLeft => ("\u{e0b6}", " "),
            Self::CapRight => ("\u{e0b4}", " "),
        };
        if plain { fallback } else { nerd }
    }
}
