#!/usr/bin/env python3
"""Embed the approved fixture corpus; the executable never reads reference files."""
import argparse
import base64
import json
import textwrap
import zlib

from demo_fixture import ROOT, load


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    corpus = load()
    raw = json.dumps(corpus, ensure_ascii=False, separators=(',', ':')).encode()
    compressor = zlib.compressobj(9, wbits=-15)  # NSData uses raw DEFLATE, without zlib headers.
    payload = base64.b64encode(compressor.compress(raw) + compressor.flush()).decode()
    output = '// Generated by scripts/embed_demo.py; do not edit. Explicit demo mode only.\n'
    output += 'enum DemoAssets {\n  static let payload = """\n'
    output += textwrap.indent('\n'.join(textwrap.wrap(payload, 76)), '    ')
    output += '\n    """\n}\n'
    target = ROOT / 'backend/Sources/Backend/DemoAssets.generated.swift'
    if args.check:
        assert target.read_text() == output, 'Embedded demo assets changed; regenerate explicitly'
    else:
        target.write_text(output)
    print('Embedded demo corpus verified')


if __name__ == '__main__':
    main()
