#!/usr/bin/env python3
"""Compile the small backend API definition into both native DTOs and JSON Schema."""
import argparse
import json
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[1]
SPEC = json.loads((ROOT / "contract/api.json").read_text())
PRIMITIVES = {"String": "String", "Bool": "bool", "UInt64": "u64", "UInt8": "u8", "Double": "f64"}


def snake(name):
    return re.sub(r"(?<!^)([A-Z])", r"_\1", name).lower()


def camel(name):
    first, *rest = name.split("_")
    return first + "".join(part.title() for part in rest)


def pascal(name):
    value = camel(name)
    return value[0].upper() + value[1:]


def native(kind, rust=False):
    if kind.endswith("?"):
        inner = native(kind[:-1], rust)
        return f"Option<{inner}>" if rust else f"{inner}?"
    if kind.startswith("["):
        inner = native(kind[1:-1], rust)
        return f"Vec<{inner}>" if rust else f"[{inner}]"
    return PRIMITIVES.get(kind, kind) if rust else kind


def validate_spec():
    names = list(PRIMITIVES)
    for group in ("enums", "records", "unions"):
        names.extend(SPEC[group])
    assert len(names) == len(set(names)), "Duplicate type names"
    for group in ("records", "unions"):
        for name, fields in SPEC[group].items():
            assert re.fullmatch(r"[A-Z][A-Za-z0-9]*", name), name
            for key, kind in fields.items():
                assert re.fullmatch(r"[a-z][A-Za-z0-9_]*", key), key
                assert kind.strip("[]?") in names, kind
    assert SPEC["maxMessageBytes"] == 1048576


def swift_source():
    out = ["// Generated by scripts/generate.py. Do not edit.", "import Foundation", "",
           f"public let apiVersion: UInt64 = {SPEC['version']}",
           f"public let maxMessageBytes = {SPEC['maxMessageBytes']}", "",
           "private struct WireKey: CodingKey {",
           "  let stringValue: String", "  var intValue: Int? { nil }",
           "  init(_ value: String) { stringValue = value }",
           "  init?(stringValue: String) { self.init(stringValue) }",
           "  init?(intValue: Int) { return nil }", "}", "",
           "private func checkKeys(_ decoder: Decoder, _ allowed: Set<String>) throws {",
           "  let box = try decoder.container(keyedBy: WireKey.self)",
           "  guard Set(box.allKeys.map(\\.stringValue)).isSubset(of: allowed) else {",
           '    throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: "Unknown field"))',
           "  }", "}", ""]
    for name, values in SPEC["enums"].items():
        out.append(f"public enum {name}: String, Codable, Sendable, CaseIterable {{")
        out.extend(f'  case {camel(v)} = "{v}"' for v in values)
        out.extend(["}", ""])
    for name, fields in SPEC["records"].items():
        out.append(f"public struct {name}: Codable, Sendable, Equatable {{")
        out.extend(f"  public var {key}: {native(kind)}" for key, kind in fields.items())
        params = [f"{key}: {native(kind)}" + (" = nil" if kind.endswith("?") else "") for key, kind in fields.items()]
        out.append("  public init(" + ", ".join(params) + ") {")
        out.extend(f"    self.{key} = {key}" for key in fields)
        out.extend(["  }", "  public init(from decoder: Decoder) throws {"])
        out.append("    try checkKeys(decoder, [" + ", ".join(json.dumps(key) for key in fields) + "])")
        if fields:
            out.append("    let box = try decoder.container(keyedBy: WireKey.self)")
        for key, kind in fields.items():
            method = "decodeIfPresent" if kind.endswith("?") else "decode"
            out.append(f'    {key} = try box.{method}({native(kind.rstrip("?"))}.self, forKey: WireKey("{key}"))')
        out.extend(["  }", "}", ""])
    for name, variants in SPEC["unions"].items():
        out.append(f"public enum {name}: Codable, Sendable, Equatable {{")
        out.extend(f"  case {camel(tag)}({kind})" for tag, kind in variants.items())
        out.extend(["  public var tag: String {", "    switch self {"])
        out.extend(f'    case .{camel(tag)}: "{tag}"' for tag in variants)
        out.extend(["    }", "  }"])
        out.extend(["  public init(from decoder: Decoder) throws {",
                    '    try checkKeys(decoder, ["type", "data"])',
                    "    let box = try decoder.container(keyedBy: WireKey.self)",
                    '    switch try box.decode(String.self, forKey: WireKey("type")) {'])
        out.extend(f'    case "{tag}": self = .{camel(tag)}(try box.decode({kind}.self, forKey: WireKey("data")))'
                   for tag, kind in variants.items())
        out.extend(['    default: throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: "Unknown message type"))',
                    "    }", "  }", "  public func encode(to encoder: Encoder) throws {",
                    "    var box = encoder.container(keyedBy: WireKey.self)", "    switch self {"])
        for tag in variants:
            out.extend([f"    case .{camel(tag)}(let value):",
                        f'      try box.encode("{tag}", forKey: WireKey("type"))',
                        '      try box.encode(value, forKey: WireKey("data"))'])
        out.extend(["    }", "  }", "}", ""])
    return "\n".join(out)


def rust_source():
    out = ["// Generated by scripts/generate.py. Do not edit.", "use serde::{Deserialize, Serialize};",
           f"pub const API_VERSION: u64 = {SPEC['version']};",
           f"pub const MAX_MESSAGE_BYTES: usize = {SPEC['maxMessageBytes']};", ""]
    derive = "#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]"
    for name, values in SPEC["enums"].items():
        out.extend(["#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]",
                    '#[serde(rename_all = "snake_case")]', f"pub enum {name} {{"])
        out.extend(f"    {pascal(value)}," for value in values)
        out.extend(["}", ""])
    for name, fields in SPEC["records"].items():
        out.extend([derive, '#[serde(rename_all = "camelCase", deny_unknown_fields)]', f"pub struct {name} {{"])
        for key, kind in fields.items():
            if kind.endswith("?"):
                out.append('#[serde(skip_serializing_if = "Option::is_none")]')
            key = "r#ref" if key == "ref" else snake(key)
            out.append(f"pub {key}: {native(kind, True)},")
        out.extend(["}", ""])
    for name, variants in SPEC["unions"].items():
        out.extend([derive, '#[serde(tag = "type", content = "data", rename_all = "snake_case", deny_unknown_fields)]',
                    f"pub enum {name} {{"])
        out.extend(f"    {pascal(tag)}({kind})," for tag, kind in variants.items())
        out.extend(["}", ""])
    return "\n".join(out)


def json_type(kind):
    if kind.endswith("?"):
        return {"anyOf": [json_type(kind[:-1]), {"type": "null"}]}
    if kind.startswith("["):
        return {"type": "array", "items": json_type(kind[1:-1]), "maxItems": 32768}
    primitives = {"String": {"type": "string", "maxLength": 8192}, "Bool": {"type": "boolean"},
                  "UInt64": {"type": "integer", "minimum": 0, "maximum": 18446744073709551615},
                  "UInt8": {"type": "integer", "minimum": 0, "maximum": 255}, "Double": {"type": "number"}}
    return primitives.get(kind, {"$ref": f"#/$defs/{kind}"})


def json_schema():
    definitions = {name: {"type": "string", "enum": values} for name, values in SPEC["enums"].items()}
    for name, fields in SPEC["records"].items():
        props = {key: json_type(kind) for key, kind in fields.items()}
        if name in ("Request", "Event"):
            props["version"] = {"const": SPEC["version"]}
        if name == "Request":
            props["id"]["minimum"] = 1
        if name == "Event":
            props["sequence"]["minimum"] = 1
            props["id"]["anyOf"][0]["minimum"] = 1
        definitions[name] = {"type": "object", "additionalProperties": False, "properties": props,
                             "required": [key for key, kind in fields.items() if not kind.endswith("?")]}
    for name, variants in SPEC["unions"].items():
        definitions[name] = {"oneOf": [{"type": "object", "additionalProperties": False,
                            "properties": {"type": {"const": tag}, "data": json_type(kind)},
                            "required": ["type", "data"]} for tag, kind in variants.items()]}
    return {"$schema": "https://json-schema.org/draft/2020-12/schema", "title": "Music backend API v1",
            "oneOf": [{"$ref": "#/$defs/Request"}, {"$ref": "#/$defs/Event"}], "$defs": definitions}


def accepts(value, schema, definitions):
    """Check only the JSON Schema vocabulary emitted above; not a general validator."""
    if "$ref" in schema:
        return accepts(value, definitions[schema["$ref"].split("/")[-1]], definitions)
    for key in ("anyOf", "oneOf"):
        if key in schema:
            matches = sum(accepts(value, part, definitions) for part in schema[key])
            return matches == 1 if key == "oneOf" else matches > 0
    if "const" in schema:
        return type(value) is type(schema["const"]) and value == schema["const"]
    kind = schema["type"]
    if kind == "object":
        props = schema["properties"]
        return (isinstance(value, dict) and set(schema["required"]) <= value.keys() <= props.keys()
                and all(accepts(v, props[k], definitions) for k, v in value.items()))
    if kind == "array":
        return (isinstance(value, list) and len(value) <= schema["maxItems"]
                and all(accepts(v, schema["items"], definitions) for v in value))
    if kind == "string":
        return (isinstance(value, str) and len(value) <= schema.get("maxLength", 8192)
                and ("enum" not in schema or value in schema["enum"]))
    if kind in ("integer", "number"):
        return (type(value) in ((int,) if kind == "integer" else (int, float))
                and schema.get("minimum", float("-inf")) <= value <= schema.get("maximum", float("inf")))
    return type(value) is bool if kind == "boolean" else value is None


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    validate_spec()
    schema = json_schema()
    fixtures = json.loads((ROOT / "contract/fixtures.json").read_text())
    for group, examples in fixtures.items():
        for value in examples:
            assert accepts(value, schema, schema["$defs"]) == group.startswith("valid"), (group, value)
    swift = subprocess.run(["swift", "format", "format"], input=swift_source(), text=True, capture_output=True, check=True).stdout
    rust = subprocess.run(["rustfmt", "--edition", "2024"], input=rust_source(), text=True, capture_output=True, check=True).stdout
    outputs = {"backend/Sources/MusicContract/Generated.swift": swift,
               "frontend/src/generated.rs": rust,
               "contract/schema.json": json.dumps(schema, ensure_ascii=False, indent=2) + "\n"}
    for name, content in outputs.items():
        path = ROOT / name
        if args.check:
            assert path.exists() and path.read_text() == content, f"Stale generated file: {name}"
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    print("Contract generation and shared schema fixtures passed")


if __name__ == "__main__":
    main()
